import { defineAstroPaperConfig } from "./src/types/config";

export default defineAstroPaperConfig({
  site: {
    url: "https://erdemtuna.github.io",
    title: "Erdem Tuna",
    description: "Personal writing and notes by Erdem Tuna.",
    author: "Erdem Tuna",
    profile: "https://github.com/erdemtuna",
    ogImage: "default-og.jpg",
    lang: "en",
    timezone: "UTC",
    dir: "ltr",
  },
  posts: {
    perPage: 4,
    perIndex: 4,
    scheduledPostMargin: 0,
  },
  features: {
    lightAndDarkMode: true,
    dynamicOgImage: true,
    showArchives: true,
    showBackButton: true,
    editPost: {
      enabled: false,
    },
    search: "pagefind",
  },
  socials: [{ name: "github", url: "https://github.com/erdemtuna" }],
  shareLinks: [],
  design: {
    light: {
      background: "#faf7f0",
      foreground: "#282d27",
      muted: "#64675c",
      accent: "#52633a",
      accentForeground: "#faf7f0",
      border: "#dcdccf",
      wash: "#eaeedf",
    },
    dark: {
      background: "#20241e",
      foreground: "#f0efe5",
      muted: "#b7bcb0",
      accent: "#b5ca91",
      accentForeground: "#20241e",
      border: "#3e4736",
      wash: "#30392a",
    },
    fonts: {
      heading: 'Georgia, "Times New Roman", serif',
      body: 'Georgia, "Times New Roman", serif',
      ui: '"Segoe UI", Arial, sans-serif',
      code: 'Consolas, "Courier New", monospace',
    },
    layout: {
      siteWidthRem: 54,
      readingWidthRem: 42,
      bodySizeRem: 1.1875,
      bodyLineHeight: 1.85,
    },
  },
  home: {
    eyebrow: "Personal writing and notes",
    heading: "Erdem Tuna",
    introduction: "A place for articles and notes.",
    featuredTitle: "Featured writing",
    recentTitle: "Recent writing",
    showFeatured: true,
    showRecent: true,
    featuredLimit: 1,
    showFeaturedCover: true,
    emptyTitle: "No posts yet",
    emptyDescription: "New writing will appear here when it is published.",
  },
});
